---
title: "Geodemographics of Student List Purchases by Public Universities: A First Look "
subtitle: ""
author: 
  - Karina Salazar
  - Ozan Jaquette
  - Crystal Han
bibliography: ../bib/student_list_empirics.bib
citeproc: no
output: 
  bookdown::word_document2:    
  #bookdown::pdf_document2:
    toc: FALSE
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
eoutput: pdf_document
always_allow_html: true
csl: ../bib/apa.csl
urlcolor: blue
fontsize: 12pt
#header-includes:
#      - \usepackage{pdflscape}
#      - \usepackage{geometry}
header-includes:
      - \usepackage{floatrow}
      - \floatsetup{capposition=top}
      - \usepackage{setspace}\onehalfspacing #\doublespacing
---

# Executive Summary

Universities identify prospective undergraduate students by purchasing “student lists” from College Board, ACT, and other vendors. Student lists contain the contact information of prospects who satisfy "search filter" criteria (e.g., test score range, high school GPA, zip code) specified by the university, who can then be recruited via mail, email, or targeted social media.

Recent research suggests that student lists have surprisingly large effects on college access outcomes for millions of students each year. The College Board Student Search Service product allows accredited institutions to "license" the contact information of test-takers. @RN4739 compared SAT test-takers who opted in versus out of Student Search Service, controlling for variables like SAT score and parental education. Based on this study, College Board states that "students who connect with colleges through Student Search are 25\% more likely to enroll in 4-year colleges \ldots [and] 31% more likely to graduate in 4 years than similar students who weren’t identified through Student Search" [@cb_opt_parents]. Furthermore, "these enrollment and completion benefits associated with Search are as large or larger for Black, Hispanic, and first-generation students" [@cb_search_press]

Whereas @RN4739 examine the outcomes of test-takers who opt in versus out Search, our research examines the search filters universities specify when buying lists and the characteristics of purchased prospects. Our central thesis is that student list products are structurally racist and classist.

Structural racism is "a form of systematic racial bias embedded in the 'normal' functions of laws and social relations" [@RN4760, p. 1143], whereby processes viewed as normal or neutral systematically advantage dominant groups and disadvantage marginalized groups. Organizations and organizational processes are fundamental mechanisms of structural racism [@RN4421]. University recruiting behavior exemplifies this claim. On one hand, "predatory" for-profit colleges practice reverse-redlining [@cottom2017lower]. On the other, selective universities systematically target affluent, predominantly white schools and communities in off-campus recruiting visits [@RN4759; @RN4733]. We began the student list project to investigate the presence of structural racism in the list-buying behaviors of universities. However, @RN4772 shows that products based on algorithms are another source of structural racism. Over time, we came to the conclusion that the student list products themselves are structurally racist. In turn, these products structure the recruiting behavior of colleges and universities.

__The student list project__. We collected data by issuing public records requests to all public universities in CA, IL, MN, and TX. Data collection focused on the three largest student list vendors. For each list purchased for the purpose of undergraduate recruiting from 2016 through 2020, we requested two related pieces of data: (1) the order summary, which shows the search criteria specified for the student list purchase; and (2) the de-identified prospect-level list produced from these criteria. We address three research questions:

1. Which filter criteria (e.g., high school graduating class, SAT score range) were selected in student lists purchased by universities in our sample?
1. What are the characteristics of prospects included in student lists purchased by universities in our sample?
1. What is the relationship between student list filter criteria and the characteristics of purchased prospects?

This report analyzes student lists purchased from College Board by XX public universities, including X public research universities and Y ma/doctoral universities. We obtained XXX student list orders, which is the analysis sample for RQ1. We obtained de-identified student list data about XXXX prospects, which is the analysis sample for RQ2. We received both the order summary data and the de-identified student list data for XX orders associated with XX prospects, resulting in the analysis sample for RQ3.

__RQ1__. The search filters utilized by universities in our sample can be categorized into four bins: academic (e.g., high school GPA); geographic (e.g., state, zip code); demographic (e.g., gender); and student preferences (e.g., intended major). At minimum, most orders specified high school graduating class, one or more academic achievement filters and one or more geographic filters. 

Compared to ma/doctoral universities, the research universities in our sample tended to set higher thresholds on academic achievement criteria, were more likely to utilize demographic filters, and they utilized a broader range of (e.g., state, geodemographic "Segment," "Geomarket," metropolitan area) as means of targeting out-of-state prospects.

__RQ2__. We examined the characteristics of purchased prospects on the dimensions of ethnicity/race, household income, and geographic "locale" (e.g., urban, suburban, rural). Public research universities in our sample purchased more out-of-state prospects than in-state prospects. Compared to in-state prospects, out-of-state prospects were more affluent, more likely to identify as white or Asian, and more likely to live in suburban areas. Ma/doctoral universities in our sample primarily purchased in-state prospects and these in-state prospects were slightly less affluent than those purchased by research universities.

__RQ3__. The most important analyses of the report investigate the relationship between search filter criteria and the characteristics of purchased prospects. In contrast to RQ1 and RQ2, RQ3 faces fewer external validity concerns because a particular combination of search criteria yields the same set of prospects regardless of which university placed the order.^[One caveat to this statement is that most student list products enable universities to exclude prospects that were included in a previous order.] Analyses for RQ3 focus on four "deep dives" of commonly observed or thematically important search filter patterns: geodemographic segment; zip code; women in STEM; and targeting URM students.

_Geodemographic segment_. The College Board Segment Analysis Service (herein Segment) is an add-on set of filters that enables universities to filter prospects by the "type" of neighborhood they live in and the "type" of high school they attend. Geodemography is branch of market research that estimates the behavior of consumers based on where they live. The @RN2039 white paper on Segment illustrates that geodemography is based on problematic assumptions about segregation:

> The basic tenet of geodemography is that people with similar cultural backgrounds, means, and perspectives naturally gravitate toward one another or form relatively homogeneous communities; in other words, birds of a feather flock together. 

Segment categorizes every U.S. census tract into one of 33 "educational neighborhood clusters" (EN:51-EN:83) and categorizes every U.S. high school into one of 29 "high school clusters" (HS:51-HS:79) based on socioeconomic, demographic, and education characteristics, including historical college-going behavior. A Segment customer may, for example, purchase prospects who scored between 1100-1300 on the SAT and attend a high school in cluster HS:63. Unfortunately, Segment neighborhood and high school clusters are highly correlated with race and income.

We analyzed eight orders by a public research university that utilized the same set of Segment filters and specified very similar academic criteria across orders. These Segment orders -- resulting in XXX purchased prospects -- yielded problematic socioeconomic and racial patterns. For example, 9,126 prospects were purchased from the Philadelphia metropolitan area. These prospects lived in zip codes where the average household income was \$136,000, much higher than the metro average of \$84,000. The racial composition of purchased prospects was 70% white, 17% Asian, X% Black, and 5% Latinx. By contrast, the racial composition of public high schools in the Philadelphia metro was 44% white, 5% Asian, 35% Black, and 13% Latinx.

_Zip code_. Most student list products allow universities to filter prospects by zip code. We analyzed the racial composition of prospects that would result from a student list purchase that filtered on affluent zip codes. This analysis was based on four student lists that targeted California high school students -- each filtering for a different score range -- by a public research university. Next we restricted analyses to prospects living in the Los Angeles metro area. Finally, we compared prospects living in a zip code in the top income decile -- our hypothetical zip code filter -- to prospects living in a zip code in the bottom nine income deciles. 

Results show that filtering for affluent zip-codes leads to substantial declines in the racial diversity of prospects. This is true across several score ranges (low, medium, high). For example, for prospects with "medium" PSAT scores of 1190-1260, prospects living in a top income decile zip code were 48% white, 21% Asian, and 14% Latinx. By contrast, prospects living in the bottom 9 deciles were 27% white, 34% Asian, and 25% Latinx. Thus, the hypothetical decision to filter on affluent zip codes results in a higher share of white prospects being recruited.

_Women in STEM and targeting URM_. Our final two deep-dives, respectively, analyse purchases that target women in STEM and purchases that target underrepresented Students of Color. Orders that targeted women in STEM -- based on AP scores (4+) or based on the combination of SAT scores (1300+) and intended major -- yielded lists that largely consisted of affluent, white and Asian prospects. Orders that filtered for underrepresented students of color with relatively high SAT scores (1200 to 1380) tended to target prospects from wealthy communities. Depending on local patterns of school segregation, these purchases disproportionately excluded Students of Color attending predominantly non-white high schools.

_Discussion_. Over time, College Board Student Search Service added search filters to identify underrepresented student populations (e.g., low-income students, rural students, National Recognition Programs). In our data collection, we observed many instances of universities Student Search Service toward this end. For example, one university purchased all students in the U.S. who identify as American Indian/Alaska Native and scored between 1040-1600 on the SAT. Another university made XX purchases -- yielding XX prospects -- targeted students with family income below \$45,000 [ASU - CRYSTAL ADD]. Thus, we acknowledge that the Student Search Service product can be to increase equity in educational opportunity. Nevertheless, Student Search Service can -- intentionally or unintentionally -- easily be used in ways that harm opportunities for underrepresented student populations. Products that have a high likelihood of causing harm must be regulated.

We believe that College Board student list products are structurally racist because filters viewed as "normal" systematically benefit dominant groups and exclude underrepresented groups. 

Geographic search filters enable universities to target prospects who live in particular places. Residential segregation is a product of systemic racism. Products that target prospects based on where they live, without considering the history of racial segregation, perpetuate the racial segregation in access to educational opportunity. Zip codes are highly correlated with race and income. From an equality of educational opportunity perspective, what is the rationale for a product that enables universities to target students living in one zip code and exclude students living in the neighboring zip code?

Geodemographic filters are even more problematic. They target more precise geographies (e.g., census tract, high school) than zip code. They enable universities to target students from the "right" kind of neighborhood or school, without explicitly naming them. Rather than targeting prospects based on their educational achievement and aspirations, geodemographic filters enable universities to target prospects based on the past college-going behavior of their peers.

College Board student list products are fundamentally based on standardized tests (SAT, PSAT, AP). Rates of test-taking differ across race and class, yielding systematic inequality in who is included in the underlying database and, in turn, who is recruited by universities. The test-optional movement may exacerbate inequalities in test-taking. Moreover, College Board -- and ACT -- search filters encourage universities to filter prospects by test score, but decades of research finds that college entrance exams exhibit both racial and socioeconomic bias [CITE - KARINA].

Over the past decade, College Board -- and ACT -- have added new search filters (e.g., "[Interest In My Peers](https://signup.collegeboard.org/subscription-features/)," "[Environmental Attributes](https://www.youtube.com/watch?v=VmTU9sb4ZiY)") that facilitate micro-targeting of the "right" kind of students. Ironically, the primary reason universities value these filters is because the price of names is so high. In 2021, College Board charged \$0.50 per name. In 2022, they are transitioning to a tiered subscription model. College Board uses revenues from "these license fees to help support its mission-driven work" [@cb_opt_in]. 

College Board describes itself as a "mission-driven not-for-profit organization that connects students to college success and opportunity, founded \ldots to expand access to higher education" [@cb_about_us]. Student Search Service is literally central to the College Board mission, not some money-making side-hustle. If College Board is serious about this mission, they should eliminate problematic micro-targeting search filters and provide all names for free.

# References

<div id="refs"></div>



