library(tidyverse)
library(labelled)


# Read in data and dictionary (22895 obs. of 349 variables)
pss <- read.csv('./data/pss_1718.csv', header = TRUE, na.strings = c('', 'NA'), stringsAsFactors = F,  colClasses = c('PZIP' = 'character', 'PSTANSI' = 'character', 'PCNTY' = 'character'))
pss_dictionary <- read.csv('./data/pss_dictionary_1718.csv', header = TRUE, na.strings=c('', 'NA'), stringsAsFactors = F)

# Turn variables to lowercase
names(pss) <- tolower(names(pss))
names(pss_dictionary) <- tolower(names(pss_dictionary))
pss_dictionary <- pss_dictionary %>% mutate(names_lc = tolower(name))

# Use 0=No/1=Yes instead of 1=Yes/2=No (ie. change the 2 to 0)
pss <- pss %>% mutate(p265 = ifelse(p265 == 1, 1, 0),
                      p275 = ifelse(p275 == 1, 1, 0),
                      p285 = ifelse(p285 == 1, 1, 0),
                      p295 = ifelse(p295 == 1, 1, 0),
                      p430 = ifelse(p430 == 1, 1, 0))

# Pad leading 0's
pss <- pss %>% mutate(pstansi = str_pad(pstansi, 2, 'left', '0'))

# Label variables
for (i in names(pss)) { 
  description <- (pss_dictionary %>% filter(names_lc == i))$label
  var_label(pss[[i]]) <- description
}

# Label values
pss <- pss %>% set_value_labels( 
  csource = c('Mail' = 1,
              'Internet' = 2,
              'Regional office follow-up' = 3,
              'Computer-assisted telephone interview' = 4),
  p135 = c('Yes' = 1,
           'No' = 2),
  p265 = c('Yes' = 1,
           'No' = 2),
  p275 = c('Yes' = 1,
           'No' = 2),
  p285 = c('Yes' = 1,
           'No' = 2),
  p295 = c('Yes' = 1,
           'No' = 2),
  p420 = c('Yes' = 1, 
           'No' = 2),
  p425 = c('Yes' = 1, 
           'No' = 2),
  p430 = c('Yes' = 1,
           'No' = 2),
  p435 = c('Yes' = 1,
           'No' = 2),
  p440 = c('Valid Skip' = -1,
           'Roman Catholic' = 1,
           'African Methodist Episcopal' = 2,
           'Amish' = 3,
           'Assembly of God' = 4,
           'Baptist' = 5,
           'Brethren' = 6,
           'Calvinist' = 7,
           'Christian (no specific denomination)' = 8,
           'Church of Christ' = 9,
           'Church of God' = 10,
           'Church of God in Christ' = 11,
           'Church of the Nazarene' = 12,
           'Disciples of Christ' = 13,
           'Episcopal' = 14,
           'Friends' = 15, 
           'Greek Orthodox' = 16,
           'Islamic' = 17,
           'Jewish' = 18,
           'Latter Day Saints' = 19,
           'Lutheran Church - Missouri Synod' = 20, 
           'Evangelical Lutheran Church in America' = 21,
           'Wisconsin Evangelical Lutheran Synod' = 22,
           'Other Lutheran' = 23,
           'Mennonite' = 24, 
           'Methodist' = 25, 
           'Pentecostal' = 26,
           'Presbyterian' = 27, 
           'Seventh-Day Adventist' = 28,
           'Other' = 29),
  p445 = c('Valid Skip' = -1,
           'Parochial' = 1,
           'Diocesan' = 2,
           'Private' = 3),
  p450 = c('Does belong to an organization/association' = 0,
           'Does not belong to an organization/association' = 1), 
  p455 = c('Not member' = 0,
           'Member' = 1), 
  p460 = c('Not member' = 0,
           'Member' = 1),
  p465 = c('Not member' = 0,
           'Member' = 1),
  p467 = c('Not member' = 0,
           'Member' = 1),
  p468 = c('Not member' = 0,
           'Member' = 1),
  p470 = c('Not member' = 0,
           'Member' = 1),
  p475 = c('Not member' = 0,
           'Member' = 1),
  p480 = c('Not member' = 0,
           'Member' = 1),
  p485 = c('Not member' = 0,
           'Member' = 1),
  p490 = c('Not member' = 0,
           'Member' = 1),
  p492 = c('Not member' = 0,
           'Member' = 1),
  p495 = c('Not member' = 0,
           'Member' = 1),
  p500 = c('Not member' = 0,
           'Member' = 1),
  p505 = c('Not member' = 0,
           'Member' = 1),
  p510 = c('Not member' = 0,
           'Member' = 1),
  p515 = c('Not member' = 0,
           'Member' = 1),
  p520 = c('Not member' = 0,
           'Member' = 1),
  p522 = c('Not member' = 0,
           'Member' = 1),
  p525 = c('Not member' = 0,
           'Member' = 1),
  p530 = c('Not member' = 0,
           'Member' = 1),
  p535 = c('Not member' = 0,
           'Member' = 1),
  p540 = c('Not member' = 0,
           'Member' = 1),
  p542 = c('Not member' = 0,
           'Member' = 1),
  p545 = c('Not member' = 0,
           'Member' = 1),
  p550 = c('Not member' = 0,
           'Member' = 1),
  p555 = c('Not member' = 0,
           'Member' = 1),
  p575 = c('Not member' = 0,
           'Member' = 1),
  p580 = c('Not member' = 0,
           'Member' = 1),
  p585 = c('Not member' = 0,
           'Member' = 1),
  p590 = c('Not member' = 0,
           'Member' = 1),
  p600 = c('Not member' = 0,
           'Member' = 1),
  p602 = c('Not member' = 0,
           'Member' = 1),
  p605 = c('Not member' = 0,
           'Member' = 1),
  p610 = c('Not member' = 0,
           'Member' = 1),
  p620 = c('Not member' = 0,
           'Member' = 1),
  p622 = c('Not member' = 0,
           'Member' = 1),
  p630 = c('Not member' = 0,
           'Member' = 1),
  p635 = c('Not member' = 0,
           'Member' = 1),
  p640 = c('Not member' = 0,
           'Member' = 1),
  region = c('Northeast' = 1,
             'Midwest' = 2,
             'South' = 3,
             'West' = 4),
  pstansi = c('Alabama' = '01',
              'Alaska' = '02',
              'Arizona' = '04',
              'Arkansas' = '05',
              'California' = '06',
              'Colorado' = '08',
              'Connecticut' = '09',
              'Delaware' = '10',
              'District of Columbia' = '11',
              'Florida' = '12', 
              'Georgia' = '13',
              'Hawaii' = '15',
              'Idaho' = '16',
              'Illinois' = '17',
              'Indiana' = '18', 
              'Iowa' = '19', 
              'Kansas' = '20', 
              'Kentucky' = '21',
              'Louisiana' = '22',
              'Maine' = '23',
              'Maryland' = '24',
              'Massachusetts' = '25',
              'Michigan' = '26', 
              'Minnesota' = '27', 
              'Mississippi' = '28', 
              'Missouri' = '29',
              'Montana' = '30', 
              'Nebraska' = '31', 
              'Nevada' = '32', 
              'New Hampshire' = '33', 
              'New Jersey' = '34', 
              'New Mexico' = '35', 
              'New York' = '36', 
              'North Carolina' = '37', 
              'North Dakota' = '38', 
              'Ohio' = '39', 
              'Oklahoma' = '40', 
              'Oregon' = '41', 
              'Pennsylvania' = '42', 
              'Rhode Island' = '44',
              'South Carolina' = '45', 
              'South Dakota' = '46', 
              'Tennessee' = '47', 
              'Texas' = '48', 
              'Utah' = '49',
              'Vermont' = '50', 
              'Virginia' = '51',
              'Washington' = '53',
              'West Virginia' = '54',
              'Wisconsin' = '55',
              'Wyoming' = '56'), 
  ulocale18 = c('City, large' = 11,
                'City, midsize' = 12, 
                'City, small' = 13, 
                'Suburb, large' = 21,
                'Suburb, midsize' = 22,
                'Suburb, small' = 23,
                'Town, fringe' = 31,
                'Town, distant' = 32, 
                'Town, remote' = 33, 
                'Rural, fringe' = 41,
                'Rural, distant' = 42,
                'Rural, remote' = 43),
  logr2018 = c('All ungraded' = 1, 
               'Lowest grade in school is prekindergarten' = 2,
               'Lowest grade in school is kindergarten' = 3, 
               'Lowest grade in school is transitional kindergarten' = 4,
               'Lowest grade in school is transitional first grade' = 5,
               'Lowest grade in school is 1st grade' = 6, 
               'Lowest grade in school is 2nd grade' = 7,
               'Lowest grade in school is 3rd grade' = 8, 
               'Lowest grade in school is 4th grade' = 9, 
               'Lowest grade in school is 5th grade' = 10, 
               'Lowest grade in school is 6th grade' = 11,
               'Lowest grade in school is 7th grade' = 12, 
               'Lowest grade in school is 8th grade' = 13, 
               'Lowest grade in school is 9th grade' = 14, 
               'Lowest grade in school is 10th grade' = 15, 
               'Lowest grade in school is 11th grade' = 16, 
               'Lowest grade in school is 12th grade' = 17),
  higr2018 = c('All ungraded' = 1, 
               'Highest grade in school is prekindergarten' = 2,
               'Highest grade in school is kindergarten' = 3, 
               'Highest grade in school is transitional kindergarten' = 4,
               'Highest grade in school is transitional first grade' = 5,
               'Highest grade in school is 1st grade' = 6, 
               'Highest grade in school is 2nd grade' = 7,
               'Highest grade in school is 3rd grade' = 8, 
               'Highest grade in school is 4th grade' = 9, 
               'Highest grade in school is 5th grade' = 10, 
               'Highest grade in school is 6th grade' = 11,
               'Highest grade in school is 7th grade' = 12, 
               'Highest grade in school is 8th grade' = 13, 
               'Highest grade in school is 9th grade' = 14, 
               'Highest grade in school is 10th grade' = 15, 
               'Highest grade in school is 11th grade' = 16, 
               'Highest grade in school is 12th grade' = 17),
  tabflag = c('Schools offering ungraded or grade 1 or above' = 1,
              'Schools offering no grade higher than KG' = 2), 
  typology = c('Catholic, parochial' = 1,
               'Catholic, diocesan' = 2,
               'Catholic, private' = 3, 
               'Other religious, conservative Christian' = 4,
               'Other religious, affiliated with established denominaiton' = 5,
               'Other religious, not affiliated with any denomination' = 6,
               'Nonsectarian, regular school' = 7,
               'Nonsectarian, special program' = 8, 
               'Nonsectarian, special education' = 9),
  relig = c('Catholic (P430=1 and P440=1)' = 1,
            'Other religious (P430=1 and P440 ne 1)' = 2,
            'Nonsectarian (P430=2)' = 3),
  orient = c('Roman Catholic' = 1,
             'African Methodist Episcopal' = 2, 
             'Amish' = 3, 
             'Assembly of God' = 4, 
             'Baptist' = 5,
             'Brethren' = 6, 
             'Calvinist' = 7, 
             'Christian (no specific denomination' = 8, 
             'Church of Christ' = 9,
             'Church of God' = 10,
             'Church of God in Christ' = 11,
             'Church of the Nazarene' = 12,
             'Disciples of Christ' = 13,
             'Episcopal' = 14, 
             'Friends' = 15, 
             'Greek Orthodox' = 16, 
             'Islamic' = 17, 
             'Jewish' = 18, 
             'Latter Day Saints' = 19, 
             'Lutheran Church - Missouri Synod' = 20, 
             'Evangelical Lutheran Church in America' = 21, 
             'Wisconsin Evangelical Lutheran Synod' = 22,
             'Other Lutheran' = 23, 
             'Mennonite' = 24, 
             'Methodist' = 25, 
             'Pentecostal' = 26, 
             'Presbyterian' = 27, 
             'Seventh-Day Adventist' = 28, 
             'Other' = 29, 
             'Nonsectarian' = 30), 
  diocese = c('Valid Skip' = -1,
              'Diocese of Birmingham, AL' = 0101,
              'Diocese of Mobile, AL' = 0102,
              'Archdiocese of Anchorage, AK' = 0201,
              'Diocese of Fairbanks, AK' = 0202,
              'Diocese of Juneau, AK' = 0203,
              'Diocese of Phoenix, AZ' = 0401,
              'Diocese of Tucson, AZ' = 0402,
              'Diocese of Little Rock, AR' = 0501,
              'Archdiocese of Los Angeles, CA' = 0601,
              'Archdiocese of San Francisco, CA' = 0602,
              'Diocese of Fresno, CA' = 0603,
              'Diocese of Monterey, CA' = 0604,
              'Diocese of Oakland, CA' = 0605,
              'Diocese of Orange, CA' = 0606,
              'Diocese of Sacramento, CA' = 0607,
              'Diocese of San Bernardino, CA' = 0608,
              'Diocese of San Diego, CA' = 0609,
              'Diocese of San Jose, CA' = 0610,
              'Diocese of Santa Rosa, CA' = 0611,
              'Diocese of Stockton, CA' = 0612,
              'Archdiocese of Denver, CO' = 0801,
              'Diocese of Colorado Springs, CO' = 0802,
              'Diocese of Pueblo, CO' = 0803,
              'Archdiocese of Hartford, CT' = 0901,
              'Diocese of Bridgeport, CT' = 0902,
              'Diocese of Norwich, CT' = 0903,
              'Diocese of Wilmington, DE' = 1001,
              'Archdiocese of Washington, DC' = 1101,
              'Archdiocese of Miami, FL' = 1201,
              'Diocese of Pensacola-Tallahassee, FL' = 1202,
              'Diocese of Orlando, FL' = 1203,
              'Diocese of Palm Beach, FL' = 1204,
              'Diocese of St. Augustine, FL' = 1205,
              'Diocese of St. Petersburg, FL' = 1206,
              'Diocese of Venice, FL' = 1207,
              'Archdiocese of Atlanta, GA' = 1301,
              'Diocese of Savannah, GA' = 1302,
              'Diocese of Honolulu, HI' = 1501,
              'Diocese of Boise, ID' = 1601,
              'Archdiocese of Chicago, IL' = 1701,
              'Diocese of Belleville, IL' = 1702,
              'Diocese of Joliet, IL' = 1703,
              'Diocese of Peoria, IL' = 1704,
              'Diocese of Rockford, IL' = 1705,
              'Diocese of Springfield, IL' = 1706,
              'Archdiocese of Indianapolis, IN' = 1801,
              'Diocese of Evansville, IN' = 1802,
              'Diocese of Ft. Wayne-South Bend, IN' = 1803,
              'Diocese of Gary, IN' = 1804,
              'Diocese of Lafayette, IN' = 1805,
              'Archdiocese of Dubuque, IA' = 1901,
              'Diocese of Davenport, IA' = 1902,
              'Diocese of Des Moines, IA' = 1903,
              'Diocese of Sioux City, IA' = 1904,
              'Archdiocese of Kansas City, KS' = 2001,
              'Diocese of Dodge City, KS' = 2002,
              'Diocese of Salina, KS' = 2003,
              'Diocese of Wichita, KS' = 2004,
              'Archdiocese of Louisville, KY' = 2101,
              'Diocese of Covington, KY' = 2102,
              'Diocese of Lexington, KY' = 2103,
              'Diocese of Owensboro, KY' = 2104,
              'Archdiocese of New Orleans, LA' = 2201,
              'Diocese of Alexandria, LA' = 2202,
              'Diocese of Baton Rouge, LA' = 2203,
              'Diocese of Houma-Thibodaux, LA' = 2204,
              'Diocese of Lafayette, LA' = 2205,
              'Diocese of Lake Charles, LA' = 2206,
              'Diocese of Shrevenport, LA' = 2207,
              'Diocese of Portland, ME' = 2301,
              'Archdiocese of Baltimore, MD' = 2401,
              'Archdiocese of Boston, MA' = 2501,
              'Diocese of Fall River, MA' = 2502,
              'Diocese of Springfield, MA' = 2503,
              'Diocese of Worcester, MA' = 2504,
              'Archdiocese of Detroit, MI' = 2601,
              'Diocese of Grand Rapids, MI' = 2602,
              'Diocese of Gaylord, MI' = 2603,
              'Diocese of Kalamazoo, MI' = 2604,
              'Diocese of Lansing, MI' = 2605,
              'Diocese of Marquette, MI' = 2606,
              'Diocese of Saginaw, MI' = 2607,
              'Archdiocese of St. Paul-Minneapolis, MN' = 2701,
              'Diocese of Crookston, MN' = 2702,
              'Diocese of Duluth, MN' = 2703,
              'Diocese of New Ulm, MN' = 2704,
              'Diocese of St. Cloud, MN' = 2705,
              'Diocese of Winona, MN' = 2706,
              'Diocese of Biloxi, MS' = 2801,
              'Diocese of Jackson, MS' = 2802,
              'Archdiocese of St. Louis, MO' = 2901,
              'Diocese of Jefferson City, MO' = 2902,
              'Diocese of Kansas City-St. Joseph, MO' = 2903,
              'Diocese of Springfield-Cape Girardeau, MO' = 2904,
              'Diocese of Great Falls-Billings, MT' = 3001,
              'Diocese of Helena, MT' = 3002,
              'Archdiocese of Omaha, NE' = 3101,
              'Diocese of Grand Island, NE' = 3102,
              'Diocese of Lincoln, NE' = 3103,
              'Diocese of Las Vegas, NV' = 3201,
              'Diocese of Reno, NV' = 3202,
              'Diocese of Manchester, NH' = 3301,
              'Archdiocese of Newark, NJ' = 3401,
              'Diocese of Camden, NJ' = 3402,
              'Diocese of Metuchen, NJ' = 3403,
              'Diocese of Paterson, NJ' = 3404,
              'Diocese of Trenton, NJ' = 3405,
              'Archdiocese of Santa Fe, NM' = 3501,
              'Diocese of Gallup, NM' = 3502,
              'Diocese of Las Cruces, NM' = 3503,
              'Archdiocese of New York, NY' = 3601,
              'Diocese of Albany, NY' = 3602,
              'Diocese of Brooklyn, NY' = 3603,
              'Diocese of Buffalo, NY' = 3604,
              'Diocese of Ogdensburg, NY' = 3605,
              'Diocese of Rochester, NY' = 3606,
              'Diocese of Rockville Centre, NY' = 3607,
              'Diocese of Syracuse, NY' = 3608,
              'Diocese of Charlotte, NC' = 3701,
              'Diocese of Raleigh, NC' = 3702,
              'Diocese of Bismarck, ND' = 3801,
              'Diocese of Fargo, ND' = 3802,
              'Archdiocese of Cincinnati, OH' = 3901,
              'Diocese of Cleveland, OH' = 3902,
              'Diocese of Columbus, OH' = 3903,
              'Diocese of Steubenville, OH' = 3904,
              'Diocese of Toledo, OH' = 3905,
              'Diocese of Youngstown, OH' = 3906,
              'Archdiocese of Oklahoma City, OK' = 4001,
              'Diocese of Tulsa, OK' = 4002,
              'Archdiocese of Portland, OR' = 4101,
              'Diocese of Baker, OR' = 4102,
              'Archdiocese of Philadelphia, PA' = 4201,
              'Diocese of Allentown, PA' = 4202,
              'Diocese of Altoona-Johnstown, PA' = 4203,
              'Diocese of Erie, PA' = 4204,
              'Diocese of Greensburg, PA' = 4205,
              'Diocese of Harrisburg, PA' = 4206,
              'Diocese of Pittsburg, PA' = 4207,
              'Diocese of Scranton, PA' = 4208,
              'Diocese of Providence, RI' = 4401,
              'Diocese of Charleston, SC' = 4501,
              'Diocese of Rapid City, SD' = 4601,
              'Diocese of Sioux Falls, SD' = 4602,
              'Diocese of Knoxville, TN' = 4701,
              'Diocese of Memphis, TN' = 4702,
              'Diocese of Nashville, TN' = 4703,
              'Archdiocese of San Antonio, TX' = 4801,
              'Diocese of Amarillo, TX' = 4802,
              'Diocese of Austin, TX' = 4803,
              'Diocese of Beaumont, TX' = 4804,
              'Diocese of Brownsville, TX' = 4805,
              'Diocese of Corpus Christi, TX' = 4806,
              'Diocese of Dallas, TX' = 4807,
              'Diocese of El Paso, TX' = 4808,
              'Diocese of Ft. Worth, TX' = 4809,
              'Diocese of Galveston-Houston, TX' = 4810,
              'Diocese of Lubbock, TX' = 4811,
              'Diocese of San Angelo, TX' = 4812,
              'Diocese of Tyler, TX' = 4813,
              'Diocese of Victoria, TX' = 4814,
              'Diocese of Laredo, TX' = 4815,
              'Diocese of Salt Lake, UT' = 4901,
              'Diocese of Burlington, VT' = 5001,
              'Diocese of Arlington, VA' = 5101,
              'Diocese of Richmond, VA' = 5102,
              'Archdiocese of Seattle, WA' = 5301,
              'Diocese of Spokane, WA' = 5302,
              'Diocese of Yakima, WA' = 5303,
              'Diocese of Wheeling-Charleston, WV' = 5401,
              'Archdiocese of Milwaukee, WI' = 5501,
              'Diocese of Green Bay, WI' = 5502,
              'Diocese of La Crosse, WI' = 5503,
              'Diocese of Madison, WI' = 5504,
              'Diocese of Superior, WI' = 5505,
              'Diocese of Cheyenne, WY' = 5601), 
  level = c('Elementary' = 1, 
            'Secondary' = 2, 
            'Combined elementary and secondary' = 3),
  size = c('Less than 50 students' = 1,
           '50-149 students' = 2,
           '150-299 students' = 3, 
           '300-499 students' = 4,
           '500-749 students' = 5,
           '750 students or more' = 6), 
  ucommtyp = c('City (ulocale18 = 11,12,13)' = 1,
               'Suburb (ulocale18 = 21,22,23)' = 2, 
               'Town (ulocale18 = 31,32,33)' = 3,
               'Rural (ulocale18 = 41,42,43)' = 4),
  p415 = c('Regular elementary or secondary' = 1, 
           'Montessori' = 2,
           'Special program emphasis' = 3,
           'Special education' = 4,
           'Career/technical/vocational' = 5,
           'Alternative/other' = 6,
           'Early childhood program/child care center' = 7),
  p335 = c('Yes' = 1,
           'No, it is an all-female school' = 2,
           'No, it is an all-male school' = 3),
  p345 = c('Yes' = 1,
           'No' = 2)
)

# Rename variables
pss <- pss %>% rename(offered_09 = 'p265',
                      total_09 = 'p270',
                      offered_10 = 'p275',
                      total_10 = 'p280',
                      offered_11 = 'p285',
                      total_11 = 'p290',
                      offered_12 = 'p295',
                      total_12 = 'p300',
                      total_teachers = 'numteach',
                      total_students = 'numstuds',
                      total_enrolled = 'p305',
                      total_hispanic = 'p320',
                      total_white = 'p330',
                      total_black = 'p325',
                      total_asian = 'p316',
                      total_nativehawaii = 'p318',
                      total_amerindian = 'p310',
                      total_tworaces = 'p332',
                      is_religious = 'p430',
                      religious_orientation = 'p440',
                      catholic_type = 'p445',
                      accelerated_christian_edu = 'p455',
                      amer_assoc_christian_sch = 'p460',
                      assoc_christian_sch_intl = 'p465',
                      oral_roberts = 'p520',
                      pct_amerindian = 'p_indian',
                      pct_asian = 'p_asian',
                      pct_nativehawaii = 'p_pacific',
                      pct_hispanic = 'p_hisp',
                      pct_white = 'p_white',
                      pct_black = 'p_black',
                      pct_tworaces = 'p_tr',
                      community_type = 'ucommtyp',
                      latitude = 'latitude18',
                      longitude = 'longitude18',
                      locale_code = 'ulocale18',
                      state_fips_code = 'pstansi',
                      name = 'pinst',
                      address = 'paddrs',
                      city = 'pcity',
                      state_code = 'pstabb',
                      zip_code = 'pzip',
                      county_fips_code = 'pcnty',
                      county_name = 'pcntnm',
                      address_secondary = 'pl_add',
                      pct_to_4yr = 'p360',
                      total_male = 'males',
                      school_type = 'p415',
                      ncessch = 'ppin')

# Filter variables (72 remaining variables)
pss <- pss %>% select(-starts_with('rep'), -starts_with('f_'), -matches('p\\d{3}|pfnlwt|csource'))

# Check variables
all(nchar(pss$school_id) == 8)
all(nchar(pss$zip_code) == 5)
all(nchar(pss$state_code) == 2)
all(nchar(pss$state_fips_code) == 2)
all(nchar(pss$county_fips_code) == 3)

# Codebook: https://nces.ed.gov/surveys/pss/pdf/codebook2017_18.pdf

val_labels(pss$religious_orientation)

# Looking at variable P440 (religious_orientation):
  # -1 - Valid Skip
  # 1 - Roman Catholic: https://en.wikipedia.org/wiki/Catholic_Church
  # 2 - African Methodist Episcopal: https://en.wikipedia.org/wiki/African_Methodist_Episcopal_Church
  # 3 - Amish: https://en.wikipedia.org/wiki/Amish
  # 4 - Assembly of God: https://en.wikipedia.org/wiki/Assemblies_of_God
  # 5 - Baptist: https://en.wikipedia.org/wiki/Baptists
  # 6 - Brethren: https://en.wikipedia.org/wiki/Church_of_the_Brethren
  # 7 - Calvinist: https://en.wikipedia.org/wiki/Calvinism
  # 8 - Christian (no specific denomination)
  # 9 - Church of Christ: https://en.wikipedia.org/wiki/Churches_of_Christ
  # 10 - Church of God: https://en.wikipedia.org/wiki/Church_of_God
  # 11 - Church of God in Christ
  # 12 - Church of the Nazarene: https://en.wikipedia.org/wiki/Church_of_the_Nazarene
  # 13 - Disciples of Christ
  # 14 - Episcopal: https://en.wikipedia.org/wiki/Episcopal_Church_(United_States)
  # 15 - Friends: https://en.wikipedia.org/wiki/Quakers
  # 16 - Greek Orthodox: https://en.wikipedia.org/wiki/Greek_Orthodox_Church
  # 17 - Islamic: https://en.wikipedia.org/wiki/Islam
  # 18 - Jewish: https://en.wikipedia.org/wiki/Judaism
  # 19 - Latter Day Saints: https://en.wikipedia.org/wiki/The_Church_of_Jesus_Christ_of_Latter-day_Saints
  # 20 - Lutheran Church - Missouri Synod: https://en.wikipedia.org/wiki/Lutheran_Church%E2%80%93Missouri_Synod
  # 21 - Evangelical Lutheran Church in America: https://en.wikipedia.org/wiki/Evangelical_Lutheran_Church_in_America
  # 22 - Wisconsin Evangelical Lutheran Synod: https://en.wikipedia.org/wiki/Wisconsin_Evangelical_Lutheran_Synod
  # 23 - Other Lutheran: https://en.wikipedia.org/wiki/Lutheranism
  # 24 - Mennonite: https://en.wikipedia.org/wiki/Mennonites
  # 25 - Methodist: https://en.wikipedia.org/wiki/Methodism
  # 26 - Pentecostal: https://en.wikipedia.org/wiki/Pentecostalism
  # 27 - Presbyterian: https://en.wikipedia.org/wiki/Presbyterianism
  # 28 - Seventh-Day Adventist: https://en.wikipedia.org/wiki/Seventh-day_Adventist_Church
  # 29 - Other

# https://en.wikipedia.org/wiki/Christian_denomination
christian <- c(1:16, 19:28)  # Everything except Valid Skip, Islamic, Jewish, and Other

# From: https://drive.google.com/file/d/1Uu-19FLD9KuIbKMAsop8UVLwNaI9A8V0/view

# The U.S. Department of Education classifies conservative Christian schools
# as those that have membership in at least one of four associations (Kena et al., 2016): 
  # Accelerated Christian Education
  # American Association of Christian Schools
  # Association of Christian Schools International
  # Oral Roberts University Education Fellowship

# Add religious affiliation
pss <- pss %>% mutate(is_christian = ifelse(religious_orientation %in% christian, 1, 0),
                      is_conservative = ifelse(accelerated_christian_edu == 1 | amer_assoc_christian_sch == 1 | assoc_christian_sch_intl == 1 | oral_roberts == 1, 1, 0))

pss <- pss %>% mutate(
  religion_5 = case_when(
    is_religious == 0 ~ 'nonsectarian',
    religious_orientation == 1 ~ 'catholic',
    is_conservative == 1 ~ 'conservative_christian',
    is_christian == 1 ~ 'other_christian',
    TRUE ~ 'other_religion'
  ),
  religion_4 = ifelse(religion_5 %in% c('other_christian', 'other_religion'), 'other_religion', religion_5),
  religion = case_when(
    religion_5 %in% c('conservative_christian', 'other_christian') ~ 'christian',
    religion_5 == 'other_religion' ~ 'other',
    TRUE ~ religion_5
  )
)

View(pss %>% group_by(religion, is_christian, is_conservative) %>% summarise(count = n()))
table(pss$religion_5)
table(pss$religion_4)  # (old) other = other_christian + other_religion
table(pss$religion)  # (new) christian = conservative_christian + other_christian

# Religion categories:
  # Nonsectarian: 7317
  # Catholic: 5324+16=5340 (There are 16 Catholic schools that also belong to 4 Conservative Christian associations but would count them as Catholic instead of Conservative Christian)
  # Conservative Christian: 2829+60=2889 (There are 60 belonging to one of 4 Conservative Christian associations whose religious affiliation is either Other or Islamic)
    View(pss %>% filter(is_christian == 0, is_conservative == 1) %>% select(religious_orientation, accelerated_christian_edu, amer_assoc_christian_sch, assoc_christian_sch_intl, oral_roberts) %>% arrange(religious_orientation))
  # Other Christian: 6379
  # Other religion-oriented: 970

# Export data
pss <- as_tibble(x = pss)
saveRDS(pss, file = './data/pss_1718.RDS')
